development:
  adapter: postgresql
  database: kuhsaft_development
  username: screenconcept
  password:
  host: localhost
  encoding: unicode
  pool: 5
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  database: kuhsaft_test
  username: screenconcept
  password:
  host: localhost
  encoding: unicode
  pool: 5
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>
